# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# https://github.com/elastic/beats/blob/master/.appveyor.yml

# version format
version: 1.0.{build}

before_build:
- choco install golang
- choco install opencover.portable
- choco install codecov


# to run your custom scripts instead of automatic MSBuild
build_script:
# Compile
  - appveyor AddCompilationMessage "Starting Compile"
  - ps: .\agent\src\win\build.ps1
  - appveyor AddCompilationMessage "Compile Success"

test_script:
# Unit tests
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"YourTestDll -noshadow" -output:"coverage.xml" -filter:"+[YourSUTNamepace*]* -[YourTestNamespace*]*"

# To disable deployment
deploy: off

# Notifications should only be setup using the AppVeyor UI so that
# forks can be created without inheriting the settings.